Scats Notebook

In [29]:
import pandas as pd
from datetime import datetime, timedelta

site_id = 2368

# Read the Signal Phasing data.CSV file as dataframe 
Signal3df = pd.read_csv('C:/Users/nsdsc0/OneDrive - WSP O365/DATA_ANALYTICS/Python/SCATS/WEST_20230308.SM.csv')

Signal3df
  
# Convert 'Cycle_starttime' and 'Date' columns to datetime format

Signal3df['Cycle_ starttime'] = pd.to_datetime(Signal3df['Cycle_ starttime'])

Signal3df['Date'] = pd.to_datetime(Signal3df['Date'])

# Round the 'Cycle_starttime' column to the nearest 5-minute interval
Signal3df['Rounded_Time'] = Signal3df['Cycle_ starttime'].dt.floor('5T')

# Create a new column by combining the 'Date' column and the rounded time
#Signaldf['Combined_DateTime'] = pd.to_datetime(Signaldf['Date']) + Signaldf['Rounded_Time'].dt.time

# Combine 'Date' and 'Rounded_Time' into a new column
Signal3df['Combined_DateTime'] = Signal3df['Date'].astype(str) + ' ' + Signal3df['Rounded_Time'].dt.time.astype(str)

# Round down the 'Combined_DateTime' column to the nearest 5 minutes
#Signaldf['Combined_DateTime'] = Signaldf['Combined_DateTime'].dt.floor('5min')

# Rename the 'Rounded_Combined_DateTime' column to 'Combined_DateTime'
Signaldf = Signal3df.rename(columns={'Rounded_Combined_DateTime': 'Combined_DateTime'})

# Move the 'Combined_DateTime' column to be the 5th column
cols = list(Signal3df.columns)
cols.insert(4, cols.pop(cols.index('Combined_DateTime')))
Signal3df = Signal3df[cols]

#Filter the rows in the 'Signal3df' DataFrame where the 'Site_ID' column that has the value "2368"
Signalfilt3_df = Signal3df[Signal3df['Site_ID'] == site_id]

# Remove duplicate values in the 'Combined_DateTime' column
Signalfilt3_df.drop_duplicates(subset='Combined_DateTime', inplace=True)

# Drop Cycle_starttime column
Signalfilt3_df = Signalfilt3_df.drop('Cycle_ starttime', axis=1)

# Convert 'Combined_DateTime' column to datetime format
#Signalfilt3_df['Combined_DateTime'] = pd.to_datetime(Signalfilt3_df['Combined_DateTime'])

# Print the updated DataFrame
Signalfilt3_df


# Specify the path and filename for the CSV file
Signalfilt3 = "C:/Users/nsdsc0/OneDrive - WSP O365/DATA_ANALYTICS/Python/SCATS/Signalfilt3.csv"

# Write the DataFrame to a CSV file
Signalfilt3_df.to_csv(Signalfilt3, index=False)


Signalfilt3_df

C:\Users\nsdsc0\AppData\Local\Temp\ipykernel_14240\4246270996.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Signalfilt3_df.drop_duplicates(subset='Combined_DateTime', inplace=True)

,Date,Site_ID,Cycle_sequence,Combined_DateTime,Planned_ cyclelength,Actual_ cyclelength,Required_ cyclelength,DS,Strategic_ approach_control_cy_time,Subsystem_No,Stretched_ phase,A,B,C,D,E,F,G,Rounded_Time
67,2023-08-03,2368,1,2023-08-03 00:00:00,60,60,60,16,20,6,A,178.0,1.0,1.0,17.0,19.0,14.0,NaN,2023-06-02 00:00:00
579,2023-08-03,2368,6,2023-08-03 00:05:00,60,60,60,27,20,6,A,176.0,1.0,1.0,19.0,19.0,14.0,NaN,2023-06-02 00:05:00
1093,2023-08-03,2368,11,2023-08-03 00:10:00,60,60,60,29,20,6,A,176.0,1.0,1.0,19.0,19.0,14.0,NaN,2023-06-02 00:10:00
1609,2023-08-03,2368,16,2023-08-03 00:15:00,60,60,60,28,21,6,A,176.0,1.0,1.0,19.0,19.0,14.0,NaN,2023-06-02 00:15:00
2122,2023-08-03,2368,21,2023-08-03 00:20:00,60,60,60,28,24,6,A,178.0,1.0,1.0,17.0,19.0,14.0,NaN,2023-06-02 00:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125877,2023-08-03,2368,1000,2023-08-03 23:35:00,60,60,60,71,20,6,D,22.0,1.0,1.0,173.0,19.0,14.0,NaN,2023-06-02 23:35:00
126389,2023-08-03,2368,1005,2023-08-03 23:40:00,60,60,60,43,22,6,D,22.0,1.0,1.0,173.0,19.0,14.0,NaN,2023-06-02 23:40:00
126897,2023-08-03,2368,1010,2023-08-03 23:45:00,60,60,60,54,22,6,D,22.0,1.0,1.0,173.0,19.0,14.0,NaN,2023-06-02 23:45:00
127405,2023-08-03,2368,1015,2023-08-03 23:50:00,60,60,60,40,20,6,D,22.0,1.0,1.0,173.0,19.0,14.0,NaN,2023-06-02 23:50:00
127919,2023-08-03,2368,1020,2023-08-03 23:55:00,60,60,60,30,20,6,D,22.0,1.0,1.0,173.0,19.0,14.0,NaN,2023-06-02 23:55:00

In [19]:
import pandas as pd
from datetime import datetime, timedelta

# Read the Traffic Volume data.CSV file as dataframe 

TraffCountCHK3df = pd.read_csv('C:/Users/nsdsc0/OneDrive - WSP O365/DATA_ANALYTICS/Python/SCATS/WEST_20230308.VS.csv')
TraffCountCHK3df


# Convert 'Start_time' column to datetime format
TraffCountCHK3df['Start_time'] = pd.to_datetime(TraffCountCHK3df['Start_time'])

# Create a new column 'Combined_DateTime' by combining 'Date' and 'Start_time'
TraffCountCHK3df['Combined_DateTime'] = TraffCountCHK3df['Date'].astype(str) + ' ' + TraffCountCHK3df['Start_time'].dt.time.astype(str)

# Convert 'Combined_DateTime' column to datetime format
TraffCountCHK3df['Combined_DateTime'] = pd.to_datetime(TraffCountCHK3df['Combined_DateTime'])

# Round 'Combined_DateTime' column down to the nearest 5 minutes
TraffCountCHK3df['Rounded_Combined_DateTime'] = TraffCountCHK3df['Combined_DateTime'].dt.floor('5min')

#Filter the rows in the 'TraffCount3df' DataFrame where the 'Site_ID' column that has the value "2368"
filtered3_df = TraffCountCHK3df[TraffCountCHK3df['Site_ID'] == site_id]

# Pivot the DataFrame to create separate columns for each unique Detector_ID
pivoted3_df = filtered3_df.pivot(index=['Combined_DateTime', 'Site_ID'], columns='Detector_ID', values='Traffic_Volume')

# Reset the index to make the combined DateTime and Site_ID columns regular columns
pivoted3_df = pivoted3_df.reset_index()

# Merge the pivoted DataFrame back into the original DataFrame based on the combined DateTime and Site_ID columns
merged3_df = filtered3_df.merge(pivoted3_df, on=['Combined_DateTime', 'Site_ID'], how='left')

# Remove the 'Combined_DateTime' column
merged3_df.drop('Combined_DateTime', axis=1, inplace=True)

# Rename the 'Rounded_Combined_DateTime' column to 'Combined_DateTime'
merged3_df.rename(columns={'Rounded_Combined_DateTime': 'Combined_DateTime'}, inplace=True)

# Drop the 'Detector_ID' column
merged3_df.drop('Detector_ID', axis=1, inplace=True)

# Remove duplicate values in the 'Combined_DateTime' column
merged3_df.drop_duplicates(subset='Combined_DateTime', inplace=True)

# Drop Cycle_starttime column
merged3_df = merged3_df.drop(['Start_time', 'Traffic_Volume'], axis=1)

# Convert 'Combined_DateTime' column to datetime format
merged3_df['Combined_DateTime'] = pd.to_datetime(merged3_df['Combined_DateTime'])

# Print the updated DataFrame
print(merged3_df)

# Specify the path and filename for the CSV file
merged3 = "C:/Users/nsdsc0/OneDrive - WSP O365/DATA_ANALYTICS/Python/SCATS/merged3.csv"

# Write the DataFrame to a CSV file
merged3_df.to_csv(merged3, index=False)

           Date  Site_ID  Error   Combined_DateTime  2368-1  2368-10  2368-11  \
0     8/03/2023     2368  False 2023-08-03 00:00:00       4        7       23
24    8/03/2023     2368  False 2023-08-03 00:05:00      13        4       17
48    8/03/2023     2368  False 2023-08-03 00:10:00      19        8       12
72    8/03/2023     2368  False 2023-08-03 00:15:00       4        3       22
96    8/03/2023     2368  False 2023-08-03 00:20:00       6        4       10
...         ...      ...    ...                 ...     ...      ...      ...
6792  8/03/2023     2368  False 2023-08-03 23:35:00       6        3       16
6816  8/03/2023     2368  False 2023-08-03 23:40:00       7        4        8
6840  8/03/2023     2368  False 2023-08-03 23:45:00       5        4       13
6864  8/03/2023     2368  False 2023-08-03 23:50:00       4        0        8
6888  8/03/2023     2368  False 2023-08-03 23:55:00       3        3        4

      2368-12  2368-13  2368-14  ...  2368-22  2368-23  2368-24  2368-3  \
0          27        1       12  ...       85        2        1      11
24         16        1        7  ...       32        4        0       8
48         21        3        5  ...       35        1        0      12
72          7        0        7  ...       33        5        1       9
96         12        1        5  ...       29       10        1       8
...       ...      ...      ...  ...      ...      ...      ...     ...
6792        8        8       22  ...       37        2        1       6
6816        9        8       19  ...       50        2        4       4
6840        7        2       13  ...       64        0        2       1
6864        8        6       12  ...       50        0        0       5
6888        9        4       20  ...       72        1        0       5

      2368-4  2368-5  2368-6  2368-7  2368-8  2368-9
0         16       0      20     120      23       9
24        13       0       6      30      17      13
48         8       0       4      28      20       8
72        15       0       3      24      23      10
96        11       0       3      25      18       6
...      ...     ...     ...     ...     ...     ...
6792      13       0      18      38      27       8
6816      12       0      23      62      10      10
6840      10       0       3      86      15       6
6864      11       0       6      69      13      14
6888      11       0       1      75      21      11

[288 rows x 28 columns]

In [27]:
# Convert datetime column to string in both dataframes
Signalfilt3_df['Combined_DateTime'] = Signalfilt3_df['Combined_DateTime'].astype(str)
merged3_df['Combined_DateTime'] = merged3_df['Combined_DateTime'].astype(str)

# Merge the Signalfilt3_df (Signal Phasing data) and the merged3_df (Traffic Volume data)

Newmerged5_df = Signalfilt3_df.merge(merged3_df, on='Combined_DateTime')
print(Newmerged5_df)

# Specify the path and filename for the CSV file
Newmerged5 = "C:/Users/nsdsc0/OneDrive - WSP O365/DATA_ANALYTICS/Python/SCATS/Newmerged5.csv"

# Write the DataFrame to a CSV file
Newmerged5_df.to_csv(Newmerged5, index=False)

        Date_x  Site_ID_x  Cycle_sequence    Combined_DateTime  \
0   2023-08-03       2368               1  2023-08-03 00:00:00
1   2023-08-03       2368               6  2023-08-03 00:05:00
2   2023-08-03       2368              11  2023-08-03 00:10:00
3   2023-08-03       2368              16  2023-08-03 00:15:00
4   2023-08-03       2368              21  2023-08-03 00:20:00
..         ...        ...             ...                  ...
283 2023-08-03       2368            1000  2023-08-03 23:35:00
284 2023-08-03       2368            1005  2023-08-03 23:40:00
285 2023-08-03       2368            1010  2023-08-03 23:45:00
286 2023-08-03       2368            1015  2023-08-03 23:50:00
287 2023-08-03       2368            1020  2023-08-03 23:55:00

     Planned_ cyclelength  Actual_ cyclelength  Required_ cyclelength  DS  \
0                      60                   60                     60  16
1                      60                   60                     60  27
2                      60                   60                     60  29
3                      60                   60                     60  28
4                      60                   60                     60  28
..                    ...                  ...                    ...  ..
283                    60                   60                     60  71
284                    60                   60                     60  43
285                    60                   60                     60  54
286                    60                   60                     60  40
287                    60                   60                     60  30

     Strategic_ approach_control_cy_time  Subsystem_No  ... 2368-22  2368-23  \
0                                     20             6  ...      85        2
1                                     20             6  ...      32        4
2                                     20             6  ...      35        1
3                                     21             6  ...      33        5
4                                     24             6  ...      29       10
..                                   ...           ...  ...     ...      ...
283                                   20             6  ...      37        2
284                                   22             6  ...      50        2
285                                   22             6  ...      64        0
286                                   20             6  ...      50        0
287                                   20             6  ...      72        1

     2368-24  2368-3  2368-4  2368-5  2368-6  2368-7 2368-8 2368-9
0          1      11      16       0      20     120     23      9
1          0       8      13       0       6      30     17     13
2          0      12       8       0       4      28     20      8
3          1       9      15       0       3      24     23     10
4          1       8      11       0       3      25     18      6
..       ...     ...     ...     ...     ...     ...    ...    ...
283        1       6      13       0      18      38     27      8
284        4       4      12       0      23      62     10     10
285        2       1      10       0       3      86     15      6
286        0       5      11       0       6      69     13     14
287        0       5      11       0       1      75     21     11

[288 rows x 46 columns]